---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: API Documentation for Location Management System
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        stripe_id:
          type: string
        address_line1:
          type: string
        address_line2:
          type: string
          nullable: true
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
      required:
      - id
      - name
      - stripe_id
      - address_line1
      - city
      - state
      - postal_code
      - country
    LocationInput:
      type: object
      properties:
        name:
          type: string
        address_line1:
          type: string
        address_line2:
          type: string
          nullable: true
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
      required:
      - name
      - address_line1
      - city
      - state
      - postal_code
      - country
    User:
      type: object
      properties:
        email:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
    UserInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
      required:
      - email
      - password
      - password_confirmation
    Error:
      type: object
      properties:
        error:
          type: string
        status:
          type: integer
    SuccessResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
        data:
          type: object
  securitySchemes:
    Bearer:
      description: JWT token authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000
tags:
- name: Authentication
  description: User authentication endpoints
- name: Locations
  description: Location management endpoints
paths:
  "/api/locations":
    get:
      summary: List locations
      tags:
      - Locations
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: locations found
          content:
            application/json:
              schema:
                type: object
                properties:
                  locations:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Location"
                  meta:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                      current_page:
                        type: integer
                      per_page:
                        type: integer
                      next_page:
                        type: integer
                        nullable: true
                      prev_page:
                        type: integer
                        nullable: true
    post:
      summary: Creates a location
      tags:
      - Locations
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: location created
        '401':
          description: unauthorized
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  "$ref": "#/components/schemas/LocationInput"
              required:
              - location
  "/api/signup":
    post:
      summary: Creates a user account
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/api/login":
    post:
      summary: Creates a session (login)
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/logout":
    delete:
      summary: Ends the session (logout)
      tags:
      - Authentication
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: logged out successfully
        '401':
          description: unauthorized
